title: HSG-AIML
description: >- # this means to ignore newlines until "baseurl:"
  Research activities at the chair Artificial Intelligence & Machine Learning at the Institute of Computer Science of the University of St. Gallen.

github_username:  hsg-aiml

minima:
  date_format: "%b %-d, %Y"

show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - research.md
  - theses.md
  - posts.md